/////
#ifndef _IOCTL_H_05703_ BASHBD_1UIWQ1_4763_ 1NJKDH256_801_ 
#define   _IOCTL_H_05703_ BASHBD_1UIWQ1_4763_ 1NJKDH256_801_ 
#define   IOCTL_PRINT_DEBUG_ MESS CTL_CODE ( \FILE_DEVICE_UNKNOWN, 0x701, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define   IOCTL_CHANGE_IRQL CTL_CODE ( \ FILE_DEVICE_UNKNOWN, 0x702, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define   IOCTL_MAKE_SYSTEM_CRASH CTL_CODE ( \ FILE_DEVICE_UNKNOWN, 0x703, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define   IOCTL_TOUCH_PORT_378H CTL_CODE ( \ FILE_DEVICE_UNKNOWN, 0x704, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define   IOCTL_SEND_BYTE_TO_USER CTL_CODE ( \ FILE_DEVICE_UNKNOWN, 0x705, METHOD_BUFFERED, FILE_ANY_ACCESS )
 #endif
